name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]   # restrict to your main branch

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'

      - name: Install deps
        run: npm ci
        working-directory: ./arc-site

      - name: Build
        run: npm run build
        working-directory: ./arc-site

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./arc-site/dist
          publish_branch: gh-pages